mod buffer;
mod change;
mod color;
mod history;
mod key;
mod mode;
mod recorder;
mod regex;
mod registry;
mod selection;
mod terminal;
mod ui;
mod view;
mod window;

pub use buffer::*;
pub use change::*;
pub use color::*;
pub use history::*;
pub use key::*;
pub use mode::*;
pub use recorder::*;
pub use regex::*;
pub use registry::*;
pub use selection::*;
pub use terminal::*;
pub use ui::*;
pub use view::*;
pub use window::*;

pub type CowStr<'a> = std::borrow::Cow<'a, str>;
